bookers2-debug/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to=>'home#top'
  get 'home/about' => 'home#about'

  get 'users/:id/follows' => 'relationships#show',as: 'follows'
  get 'users/:id/followers' => 'relationships#index',as: 'followers'
  resources :relationships
  resources :users do
    resource :relationships, only: [:create,:destroy]
    get :search, on: :collection
  end
  resources :books do
      resource :favorites, only: [:create, :destroy,]
      resource :books, only: [:create, :destroy]
  	  resources :book_comments
  end
end

bookers2-debug/app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment,presence: true
end

bookers2-debug/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
	    @booker = Book.find(params[:book_id])
	    @book_comment = @booker.book_comments.build(comment_params)
	    @book_comment.user_id = current_user.id
	    if @book_comment.save
     		render :show
    	end
	end

	def destroy
		@book_comment = BookComment.find(params[:id]) 
    	if @book_comment.destroy
      		render :show
    	end
	end

	private
	def comment_params
	    params.require(:book_comment).permit(:comment, :book_id, :user_id)
	end
end

bookers2-debug/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2-debug/app/views/book_comments/_comment.html.erb
<%= form_with(model: [booker, book_comment] ) do |f| %>
<div>
    <%= f.text_area :comment %>
</div>
<div class="actions">
    <%= f.submit "送信" %>
</div>
<% end %>

bookers2-debug/app/views/book_comments/_comments.html.erb
<% book_comments.each do |book_comment| %>
<tr>
    <td>
        <%= attachment_image_tag book_comment.user,:profile_image, size:"50x50", format: 'jpeg' , fallback: "no_image.jpg"%><br>
        <%= book_comment.user.name%>
    </td>
    <td>
        <%= book_comment.comment %>
    </td>
    <td>
        <% if book_comment.user_id == current_user.id %>
        <%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, remote: true, class:"btn btn-danger" %>
        <% end %>
    </td>
</tr>
<% end %>

bookers2-debug/app/views/book_comments/show.js.erb
$("#comments_area").html("<%= j(render 'comments', { book_comments: @book_comment.book.book_comments }) %>")
$("textarea").val('')