bookers2-debug/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to=>'home#top'
  get 'home/about' => 'home#about'

  get 'users/:id/follows' => 'relationships#show',as: 'follows'
  get 'users/:id/followers' => 'relationships#index',as: 'followers'
  resources :relationships
  resources :users do
    resource :relationships, only: [:create,:destroy]
    get :search, on: :collection
  end
  resources :books do
      resource :favorites, only: [:create, :destroy,]
      resource :books, only: [:create, :destroy]
  	  resources :book_comments
  end
end

bookers2-debug/app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		if params[:name].present?
	      @users = User.where('name LIKE ?', "%#{params[:name]}%")
	    else
	      @users = User.none
	    end
	end
end

bookers2-debug/app/helpers/search_helper.rb
module SearchHelper
end

bookers2-debug/app/views/search/search.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
        </nav>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <!--if文でサインインとアウト時の表示を変更-->
                <% if user_signed_in? %>
                <li>
                    <%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %>
                </li>
                <li>
                    <%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %>
                </li>
                <li>
                    <%= link_to ' log out', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
                </li>
                <% else %>
                <li>
                    <%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %>
                </li>
                <li>
                    <%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %>
                </li>
                <li>
                    <%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
                </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

    <div class="container">
        <div class="row">
        <h2>User search for '
            <%= %>'</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <% @user.each do |user| %>
                <tr>
                    <td>
                        <%= user.name %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    </div>