bookers2-debug/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to=>'home#top'
  get 'home/about' => 'home#about'

  get 'users/:id/follows' => 'relationships#show',as: 'follows'
  get 'users/:id/followers' => 'relationships#index',as: 'followers'
  resources :relationships
  resources :users do
    resource :relationships, only: [:create,:destroy]
    get :search, on: :collection
  end
  resources :books do
      resource :favorites, only: [:create, :destroy,]
      resource :books, only: [:create, :destroy]
  	  resources :book_comments
  end
end

bookers2-debug/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :name,uniqueness: { case_sensitive: :false },
    		length: { minimum: 2, maximum: 20 }
  validates :introduction,length:{maximum:50}
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(search, user_or_book) #ここでのself.はUser.を意味する
    if user_or_book == "1"
       User.where(['name LIKE ?', "%#{search}%"])
    else
       User.none
    end
  end
  def User.search(search, user_or_book, how_search)
        if user_or_book == "1"
            if how_search == "1"
                    User.where(['name LIKE ?', "%#{search}%"])
            elsif how_search == "2"
                    User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "3"
                    User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "4"
                    User.where(['name LIKE ?', "#{search}"])
            else
                    User.none
            end
         end
    end
end

bookers2-debug/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update]
  skip_before_action:logged_in_user,only:[:new,:create]

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = User.find(params[:id]).books
  end

  def edit
    @user = current_user
  end

  def update
    if  @user.update(user_params)
        flash[:notice] = "successfully"
        redirect_to user_path(params[:id])
    else
        flash.now[:alert] = "error"
        render :edit
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def search
    @user_or_book = params[:option]
    @how_search = params[:choice]
    if @user_or_book == "1"
      @users = User.search(params[:search], @user_or_book, @how_search)
    else
      @books = Book.search(params[:search], @user_or_book, @how_search)
    end
  end


  private
  def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def logged_in_user
    unless logged_in?
      redirect_to user_session_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_session_path unless @user == current_user
  end
end

bookers2-debug/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-debug/app/views/users/edit.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
        </nav>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <!--if文でサインインとアウト時の表示を変更-->
                <% if user_signed_in? %>
                <li>
                    <%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %>
                </li>
                <li>
                    <%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %>
                </li>
                <li>
                    <%= link_to ' log out', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
                </li>
                <% else %>
                <li>
                    <%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %>
                </li>
                <li>
                    <%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %>
                </li>
                <li>
                    <%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
                </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>
<h2>User info</h2>
<%= form_for(@user) do |f| %>
<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
<h3>
    <%= @user.errors.count %>error occurrence</h3>
<!--エラーメッセ-->
<ul>
    <% @user.errors.full_messages.each do |message| %>
    <li>
        <%= message %>
    </li>
    <% end %>
</ul>
<% end %>
<!-- エラーメッセージ表示-->
<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
</div>
<div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
</div>
<div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

bookers2-debug/app/views/users/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
        </nav>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <!--if文でサインインとアウト時の表示を変更-->
                <% if user_signed_in? %>
                <li>
                    <%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %>
                </li>
                <li>
                    <%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %>
                </li>
                <li>
                    <%= link_to ' log out', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
                </li>
                <% else %>
                <li>
                    <%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %>
                </li>
                <li>
                    <%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %>
                </li>
                <li>
                    <%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
                </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>
<div class="container">
    <p id="notice"></p>
    <div class="row">
        <div class="row">
            <div class="row">
                <%= form_tag(search_users_path,:method => 'get') do %>
                <%= text_field_tag :search %>
                <%= select_tag(:option, options_for_select([["User", "1"],["Book","2"]]))%>
                <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
                <%= submit_tag '検索', :name => nil %>
                <% end %>
            </div>
        </div>
        <div class="col-xs-3">
            <h2>User info</h2>
            <table class="table">
                <tbody>
                    <%= form_for(@user) do |f| %>
                    <tr>
                        <th>
                            <%= attachment_image_tag @user, :profile_image,size:"100x100", fallback: "no_image.jpg" %>
                        </th>
                    </tr>
                    <th>name</th>
                    <th>
                        <%= @user.name %>
                    </th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th>
                            <%= @user.introduction %>
                        </th>
                    </tr>
                    <% if @user.id == current_user.id %>
                    <tr>
                        <th>follows</th>
                        <th>
                            <%= link_to @user.followings.count,follows_path(@user) %>
                        </th>
                    </tr>
                    <tr>
                        <th>followers</th>
                        <th>
                            <%= link_to @user.followers.count,followers_path(@user)%>
                        </th>
                    </tr>
        </div>
        <%end%>
        <% end %>
        </tbody>
        </table>
        <% if @user.id == current_user.id %>
        <div class="row">
            <%= link_to'edit',edit_user_path(current_user.id), class: 'btn btn-primary col-xs-12'%>
        </div>
        <%else%>
        <div class="row">
            <%= link_to'edit',user_path(current_user.id), class: 'btn btn-primary col-xs-12'%>
        </div>
        <% end %>
        <div class="row">
            <h2>New book</h2>
            <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <p>error</p>
            <% end %>
            <div>
                <h4>Title</h4>
                <%= f.text_field :title, class: 'col-xs-12'%>
            </div>
            <div>
                <h4>Opinion</h4>
                <%= f.text_area :body ,class: 'col-xs-12'%>
            </div><br>
            <div>
                <%= f.submit 'Create Book',class: 'btn btn-primary col-xs-12' %>
            </div>
            <% end %>
        </div>
    </div>
    <div class="col-xs-9">
        <h2>Users</h2>
        <table class="table ">
            <thead>
                <th>image</th>
                <th>name</th>
                <th></th>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <th>
                    <%=  attachment_image_tag user,:profile_image,size:'40x40',fallback: "no_image.jpg" %>
                </th>
                <th>
                    <%= user.name %>
                </th>
                <th>フォロー数：
                    <%= user.followings.count %>
                </th>
                <th>フォロワー数：
                    <%= user.followers.count%>
                </th>
                <th>
                    <% unless current_user == user%>
                    <% if current_user.following?(user) %>
                    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
                    <%end%>
                    <% else %>
                    <%= form_for(user.relationships.build) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
                    <% end %>
                    <% end %>
                    <%end%>
                </th>
                <th>
                    <%= link_to 'Show',user_path(user.id) %>
                </th>
            </tbody>
    </div>
    <%end%>
    </table>
</div>

bookers2-debug/app/views/users/search.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
        </nav>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <!--if文でサインインとアウト時の表示を変更-->
                <% if user_signed_in? %>
                <li>
                    <%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %>
                </li>
                <li>
                    <%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %>
                </li>
                <li>
                    <%= link_to ' log out', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
                </li>
                <% else %>
                <li>
                    <%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %>
                </li>
                <li>
                    <%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %>
                </li>
                <li>
                    <%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
                </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

<body>
    <div class="container">
        <% if @user_or_book == "1"%>
        <h2>User search for '
            <%= params[:search]%>'</h2>
        <table class="table ">
            <thead>
                <th>image</th>
                <th>name</th>
                <th></th>
            </thead>
            <% @users.each do |user| %>
            <tbody>
                <tr>
                    <th>
                        <%=  attachment_image_tag user,:profile_image,size:'40x40',fallback: "no_image.jpg" %>
                    </th>
                    <th>
                        <%= user.name %>
                    </th>
                    <th>フォロー数：
                        <%= user.followings.count %>
                    </th>
                    <th>フォロワー数：
                        <%= user.followers.count%>
                    </th>
                    <th>
                        <% unless current_user == user%>
                        <% if current_user.following?(user) %>
                        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                        <%= hidden_field_tag :follow_id, user.id %>
                        <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
                        <%end%>
                        <% else %>
                        <%= form_for(user.relationships.build) do |f| %>
                        <%= hidden_field_tag :follow_id, user.id %>
                        <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
                        <% end %>
                        <% end %>
                        <%end%>
                    </th>
                    <th>
                        <%= link_to 'Show',user_path(user.id) %>
                    </th>
                </tr>
            </tbody>
            <% end %>
        </table>
        <% elsif @user_or_book == "2" %>
        <h2>Book search for '
            <%= params[:search]%>'</h2>
        <table class="table">
            <thead>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
            </thead>
            <% @books.each do |book| %>
            <tbody>
                <tr>
                    <th>
                        <%= link_to user_path(book.user) do %>
                        <%= attachment_image_tag book.user,:profile_image, size:"40x40", format: 'jpeg' , fallback: "no_image.jpg"%>
                        <% end %>
                    </th>
                    <th>
                        <%= link_to book.title,book_path(book.id) %>
                    </th>
                    <th>
                        <%= book.body %>
                    </th>
                    <th>
                        <%if book.favorited_by?(current_user)%>
                        <%= link_to book_favorites_path(book),method: :delete do%>
                        <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
                        <%= book.favorites.count %>
                        <% end %>
                        <%else%>
                        <%= link_to book_favorites_path(book),method: :post do%>
                        <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>
                        <%= book.favorites.count %>
                        <%end%>
                        <%end%>
                    </th>
                    <th>
                        <a>コメント数：
                            <%= book.book_comments.count %></a>
                    </th>
                </tr>
            </tbody>
            <% end %>
        </table>
        <% else %>
        <% end %>
    </div>
</body>

bookers2-debug/app/views/users/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
        </nav>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <!--if文でサインインとアウト時の表示を変更-->
                <% if user_signed_in? %>
                <li>
                    <%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %>
                </li>
                <li>
                    <%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %>
                </li>
                <li>
                    <%= link_to ' log out', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %>
                </li>
                <% else %>
                <li>
                    <%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %>
                </li>
                <li>
                    <%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %>
                </li>
                <li>
                    <%= link_to ' Sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %>
                </li>
                <li>
                    <%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %>
                </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>
<div class="container">
    <p id="notice"></p>
    <div class="row">
        <div class="row">
            <%= form_tag(search_users_path,:method => 'get') do %>
            <%= text_field_tag :search %>
            <%= select_tag(:option, options_for_select([["User", "1"],["Book","2"]]))%>
            <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
            <%= submit_tag '検索', :name => nil %>
            <% end %>
        </div>
    </div>
    <div class="col-xs-3">
        <h2>User info</h2>
        <div>
            <table class="table">
                <div class="row">
                    <tr>
                        <th>
                            <%= attachment_image_tag @user, :profile_image,size:"100x100", fallback: "no_image.jpg" %>
                        </th>
                    </tr>
                    <th>name</th>
                    <th>
                        <%= @user.name %>
                    </th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th>
                            <%= @user.introduction %>
                        </th>
                    </tr>
                    <% if @user.id == current_user.id %>
                    <tr>
                        <th>follows</th>
                        <th>
                            <%= link_to @user.followings.count,follows_path(@user) %>
                        </th>
                    </tr>
                    <tr>
                        <th>followers</th>
                        <th>
                            <%= link_to @user.followers.count,followers_path(@user)%>
                        </th>
                    </tr>
                    <%end%>
                </div>
            </table>
            <% if @user.id == current_user.id %>
            <div class="row">
                <%= link_to'edit',edit_user_path(current_user.id), class: 'btn btn-primary col-xs-12'%>
            </div>
            <%else%>
            <div class="row">
                <% unless current_user == @user %>
                <% if current_user.following?(@user) %>
                <%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
                <%= hidden_field_tag :follow_id, @user.id %>
                <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
                <% end %>
                <% else %>
                <%= form_for(current_user.relationships.build) do |f| %>
                <%= hidden_field_tag :follow_id, @user.id %>
                <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
                <% end %>
                <% end %>
                <% end %>
            </div>
            <% end %>
        </div>
        <div class="row">
            <h2>New book</h2>
            <%= form_for(@book) do |f| %>
            <% if @book.errors.any? %>
            <p>error</p>
            <% end %>
            <div>
                <h4>Title</h4>
                <%= f.text_field :title, class: 'col-xs-12'%>
            </div>
            <div>
                <h4>Opinion</h4>
                <%= f.text_area :body ,class: 'col-xs-12'%>
            </div><br>
            <div>
                <%= f.submit 'Create Book',class: 'btn btn-primary col-xs-12' %>
            </div>
            <% end %>
        </div>
    </div>
    <div class="col-xs-9">
        <h2>Books</h2>
        <table class="table ">
            <thead>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
            </thead>
            <tbody>
                <% @books.each do |book| %>
                <tr>
                    <th>
                        <%= attachment_image_tag book.user,:profile_image,size:"40x40",fallback: "no_image.jpg"%>
                    </th>
                    <th>
                        <%= link_to book.title,book_path(book.id) %>
                    </th>
                    <th>
                        <%= book.body %>
                    </th>
                    <th>
                        <a>コメント数：
                            <%= book.book_comments.count %></a>
                    </th>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div>
</div>
</div>